### ISSUE TITLE
GH1120 for Windows

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1202]
On Linux https://github.com/pwsafe/pwsafe/issues/1120 is fixed, but not on Windows.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/441c5088-5c4c-4efa-8e6c-b3a964375f90)

**Comment by ronys** [comment]
Fixed in commit 83d07dd37

**Comment by igor2x** [comment]
@ronys, today I have downloaded Password Safe v3.66-pre from 3.66.0pre branch from Github|Actions|Artifacts and installed it inside Bottles (one of Wine GUI) on Ubuntu 24.04. I did some tests and I see I still see Yes/No buttons. Is this issue really fixed?

Left: weak password warning; Right: Help | About

![image](https://github.com/pwsafe/pwsafe/assets/10895030/f76d84b6-b64e-459d-871d-ffe0ce12baab)

**Comment by igor2x** [comment]
I have downloaded today's latest pwsafe from master branch from Github/Actions and tested it on Windows 10.
The problem still persists.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/e2a9688a-3e8d-4379-bf66-d7c870ef610d)

Can you please reopen this issue?

**Comment by ronys** [comment]
Hi,

This was fixed in the Change Master Password Dialog, but not in the Master Password Setup Dialog.
Fixed in the latter in commit 0d751f212

Thanks for catching this!
