### ISSUE TITLE
Synhronize dialog has huge and cutted title text

### ISSUE THREAD

**Issue by igor2x** [pwsafe/pwsafe#1256]
Password Safe v1.19-pre from latest master branch on Ubuntu 24.04.

1. File | Synchronize.
2. Introduction dialog is opened. Click Next button.
3. Bellow dialog is opened with huge and cut text "Select another database":
![image](https://github.com/pwsafe/pwsafe/assets/10895030/3bdb195c-41eb-4102-88d5-cdaec97ced6e)

Problem is there is huge text. Maybe there is just some font that is too big for this text.

**Comment by nobugshere** [comment]
Just a note: Using 1.19pre from the current master branch, this problem is reproducible on Fedora, but, in addition,  the "back, next, and cancel" buttons are misplaced and do not work.  (The "x" at the top right does close the dialog normally.)
This problem does not appear to affect macOS.

Tested on:
macOS M1Max Sonoma 14.4.1, Xcode 15.3, wx 3.2.4 (not affected)
Fedora 39 ARM, Xfce, gcc 13.2.1, wx 3.2.4, GTK 3.24.41 (see screenshot)

![Screenshot_2024-05-06_10-17-28](https://github.com/pwsafe/pwsafe/assets/61946508/7ae96a3b-66a3-427f-b247-463918ea2c33)

**Comment by igor2x** [comment]
I just checked officially stable v1.18.2 version and it looks like this issue is not new in v1.19-pre development cycle.

Different behavior between bellow point 1 and point 2 is maybe because it may be used different version of wxWidgets,but unfortunately v1.18.2 does not yet have wxWidgets version in Help | About to really confirm this is the cause.

1. I installed Password Safe v1.18.2 from deb package on Ubuntu 22.04 (title text has huge font text, but buttons are OK):
![image](https://github.com/pwsafe/pwsafe/assets/10895030/db4fa418-1fe3-47b6-84d0-70e4b992ca1e)
with Help | About:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/e776101d-e247-41a5-aa22-a4328c1cd18b)


2. I installed Password Safe v1.18.2 from flatpak package on Ubuntu 22.04 (title text has huge font text and buttons are positioned at way too high):
![image](https://github.com/pwsafe/pwsafe/assets/10895030/7a8c9055-3f97-4717-89bf-336dc75138b8)
with Help | About:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/50529a08-8903-47a7-ac39-9d35e4d6c91f)
From [flatpak manifest file](https://github.com/flathub/org.pwsafe.pwsafe/blob/master/org.pwsafe.pwsafe.yml) I see wxWidgets version v3.2.4 is used for Password Safe v1.18.2 flatpak.

**Comment by igor2x** [comment]
I have build Password Safe v1.18.2 **flatpak** with new wxWidgets verions, but this does not fixes any problem.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/2c88a761-8455-4a0e-ab30-74d8bc4908a0)

**Comment by rafaelx** [comment]
The wxWidgets issue [19053](https://github.com/wxWidgets/wxWidgets/issues/19053) describes what we are facing in pwsafe, but as I understood from the discussion, it should be fixed in the 3.2 series.

**Comment by igor2x** [comment]
In flatpak v1.19.1 there is already wxWidgets v3.2.4 and this is still a problem.
