### ISSUE TITLE
-h/-u command line arguments ignored v3.40+

### ISSUE THREAD

**Issue by B00ze64** [pwsafe/pwsafe#231]
Good day.

I use the following command to run PasswordSafe from a USB stick:
pwsafe.exe -r MySafe.psafe3 -h Public -u Anonymous -g pwsafe_portable.cfg

Since v3.40, PasswordSafe is not using the Pwsafe_Settings/Public/Anonymous section of the settings file; it is creating new sections for each computer/user combination that I run PasswordSafe on. This is somewhat annoying; without the ability to use a single settings section, I have to redo my settings everywhere I go. Tested working fine with v3.39.

Thank you.
Best Regards,

**Comment by ronys** [comment]
This has been fixed in 3.41. See https://sourceforge.net/p/passwordsafe/bugs/1367/

**Comment by B00ze64** [comment]
I am using 3.41 geba79fa and this is still happening. Try it with the command exactly as I show above. I tested again now; still creates a section in the config and ignores the -h/-u that I specify. Can you please re-open?

**Comment by B00ze64** [comment]
Lol, you /could/ have told me to go see 1367 when I asked to re-open; it is indeed not fixed in 3.41 but under 1367 it says it will be fixed in the next release. You closed it on souceforge too early as well ;-)
